FROM osixia/openldap:1.2.4
MAINTAINER Chinthaka Deshapriya <chinthak@@cybergate.lk>

ADD bootstrap /container/service/slapd/assets/config/bootstrap
ADD certs /container/service/slapd/assets/certs
ADD environment /container/environment/01-custom
